Hourly forecast
MLH-Fellowship/prep-project-22.JUL.PREP.2 pull request #19
Opened 2022-07-20 17:41 UTC by reejuBhattacharya

Fixes Issue #1 

![image](https://user-images.githubusercontent.com/40564575/180047439-7adfe584-aa29-459b-92bb-2336cb4c0cf1.png)

2022-07-22 09:38 UTC, HetviSoni approved these changes

2022-07-22 09:49 UTC, sumana2001 requested changes
Couple of changes needed, @HetviSoni please keep a note😊
1. Why has example.env been deleted? Please keep it unchanged so that anyone who uses the repo later can understand what the env should look like.
2. Do not include package-lock.json file in the commit
3. Fix merge conflicts

2022-07-22 18:57 UTC, sumana2001 commented
<img width="1079" alt="Screenshot 2022-07-23 at 12 27 13 AM" src="https://user-images.githubusercontent.com/63084088/180505602-7dcb6fe1-1761-462b-83f6-5f2bdb59ce07.png">
This is what I see in the deploy preview. Is it the same for you? @Krishi-02 @reejuBhattacharya

2022-07-24 01:44 UTC, sumana2001 approved these changes

2022-07-24 01:44 UTC, merged